### ISSUE TITLE
Vertaisarviointi tiralabra

### ISSUE THREAD

**Issue by elonheimo** [tuukkalai/tiralabra#1]
Projekti on kopiotu githubista 8.10. klo 17

Koodi on helppolukuista ja hyvin selkeää. Lisäksi runsas määrä docstingia helpotti koodin lukemista.
Tässä muutama nosto projektista.

1.
Huffman algoritmi ei toimi testitiedostolla "simple_test.txt"
pakkaamisen ja purkamisen jälkeen tekstitiedoston sisältö on:
AABABABCBCBDBDBABAAAACCACDCDCDAAACDCDAABCAACBACAAABCABDDCBABAAAAAAAAA

2.

Huffman algoritmin binääripuun tallentamista pystyisit optimoimaan sillä tiedolla, että lehtien määrä on n+1, kun sisällötömien solmujen määrä on n.
Eli et välttämättä tarvitsisi tavua täynnä nollia erottajaksi, kun tallennat huffmankoodilla pakattua tiedostoa.

3. 
Ohjelman rakennetta on mahdollista parantaa eriyttämällä pääohjelma ja käyttöliittymä ominaisuudet omaan tiedostoonsa.

4. 

Seuraava käyttöohjeen kohta ei pidä paikkansa:

## Projektin suorittaminen

Aja Huffman-algoritmin ohjelma

```sh
poetry run invoke huffman
```

Edeltävän sijaan voisin ohjleistaa vaikka 
```sh
poetry run invoke huffmanpura [tiedostopolku]
```
```sh
poetry run invoke huffmanpakkaa [tiedostopolku]
```

Projektissa on hyvät edellytykset, ominaisuuksia vain hieman lisää niin hyvä tulee :) Ohjelmmoinnin iloa ja mukavaa syksyä!

**Comment by tuukkalai** [comment]
Kiitos vertaisarviosta!
Nämä toimi hyvänä pohjana sovellusta viimeisteltäessä ja korjauksia tehdessä :100:
