### ISSUE TITLE
Vertaisarvionti#2

### ISSUE THREAD

**Issue by VoxBorealis** [tuukkalai/tiralabra#2]
Projekti kloonattu: 12.10.2022

Kokonaisuudessaan koodisi on hyvin laadukasta ja selkeää. Kattavat Docstringit helpottavat huomattavasti koodin ymmärtämistä.

Ohjelmasi testailua olisi helpoittanut kattavammat ohjeet. Esimerksiksi itselleni ei ollut selvää, miten tiedostot tulisi syöttää ohjelmalle, ennen kuin luin koodia syvemmälle.

https://github.com/tuukkalai/tiralabra/blob/d9478ed4815b705e6083ff6c31c8302f94d7bcc4/app/huffman.py#L20

Ehkä missaan jotain tässä, mutta en näe syytä muuttaa 'syöte'-stringiä listaksi tässä tapauksessa.
Voit loopata merkkijonoja samalla syntaksilla kuin listoja. 

Kokeilin Huffman-pakkaustasi, mutta kuten viikkoraportissasi mainitsitkin, puretussa tiedostossa on lopussa ylimääräisiä merkkejä. 
Itselläni oli sama onglema aluksi, mutta sain korjattua sen formatoimalla binaaritiedoston viimeisen tavun erikseen, jonka avulla vältyin ylimääräisistä 0-biteistä.

Kokeilin tuota ratkaisua koodissasi, mutta en saanut sitä toimimaan, joten ehkä parempi ratkaisu on ehdottamasi "Tähän auttanee pakaamattoman tiedoston pituudesta kertova tavu tiedoston headeriin."

Ratkaisusi sanakirjan tallettamiseen datan kanssa näyttää toimivan mainiosti!

Hyvää työtä ja tsemppiä LZ78:n kanssa!

**Comment by tuukkalai** [comment]
Kiitos vertaisarvioinnista!
Testausta varten on lisätty mm. testausdokumenttiin informaatiota.
Hyvin bongattu tuo rivin 20 aivopieru :smile: Muualla projektissa käytetään lähes poikkeuksetta muotoa `for i in syote:`
Oletan, että syöte on ehkä ollut jotain muuta muotoa jossain kohtaa.
:100:
